export const CUTE_PLAYER_NAMES = [
  "Sweet Bunny", "Honey Muffin", "Tiny Panda", "Sugar Pebble", "Cozy Bear",
  "Cherry Blossom", "Baby Mochi", "Angel Cookie", "Fluffy Peach", "Cuddle Bug",
  "Snowy Cupcake", "Little Dove", "Cotton Candy", "Bunny Boo", "Daisy Puff",
  "Teddy Snuggles", "Peachy Pie", "Marshmallow Bean", "Cookie Sprinkles", "Moonlit Bunny",
  "Choco Puff", "Tiny Sunshine", "Pinky Paws", "Jellybean Hug", "Sweet Panda",
  "Honey Blossom", "Cupcake Bunny", "Starry Bear", "Blueberry Muffin", "Tiny Marshmallow",
  "Caramel Cloud", "Baby Waffles", "Snowflake Kiss", "Cherry Bunny", "Puffy Kitten",
  "Peach Blossom", "Sugar Bunny", "Cinnamon Roll", "Tiny Cookie", "Dreamy Panda",
  "Honey Bunny", "Vanilla Puff", "Teddy Cookie", "Sweet Pudding", "Angel Muffin",
  "Berry Snuggles", "Little Moonbeam", "Bunny Sprout", "Cocoa Bunny", "Tiny Daisy",
  "Puffy Angel", "Glitter Bunny", "Cozy Muffin", "Peachy Bunny", "Lovebug Panda",
  "Caramel Bunny", "Baby Sprinkles", "Snowy Snuggles", "Candy Blossom", "Jelly Puff",
  "Tiny Teddy", "Bunny Sparkle", "Dreamy Cupcake", "Sweetie Paws", "Honey Pebble",
  "Chubby Panda", "Little Cherry", "Sugarplum Bunny", "Vanilla Bunny", "Angel Panda",
  "Cookie Bunny", "Tiny Lovebug", "Peach Puff", "Moon Bunny", "Cozy Cupcake",
  "Teddy Blossom", "Baby Cloud", "Berry Bunny", "Marshmallow Star", "Fluffy Muffin",
  "Honey Snuggles", "Sugar Panda", "Little Buttercup", "Panda Sprinkles", "Bunny Waffles",
  "Cotton Puff", "Sweet Blossom", "Tiny Jellybean", "Cocoa Sprout", "Angel Bunny",
  "Peachy Snuggles", "Starry Muffin", "Cherry Cupcake", "Sugar Cookie", "Puffy Waffles",
  "Dream Bunny", "Honey Cupcake", "Tiny Panda Paws", "Sweet Marshmallow", "Bunny Buttercream",
  "Pink Dolphin", "Silver Bunny", "Golden Panda", "Blue Penguin", "Lavender Fox",
  "Peach Tiger", "Ivory Swan", "Mint Kitty", "Coral Bunny", "Sunny Koala",
  "Ruby Panda", "Aqua Bunny", "Velvet Dolphin", "Lilac Bear", "Crystal Kitty",
  "Cherry Fox", "Honey Penguin", "Snowy Otter", "Bubble Panda", "Dreamy Dolphin",
  "Pink Flamingo", "Frost Bunny", "Cocoa Koala", "Angel Penguin", "Maple Bunny",
  "Golden Seal", "Cotton Fox", "Ocean Panda", "Pearl Kitty", "Blue Whale",
  "Moon Bunny", "Strawberry Otter", "Velvet Panda", "Tiny Flamingo", "Lemon Bunny",
  "Star Dolphin", "Candy Koala", "Aqua Fox", "Silver Otter", "Peach Penguin",
  "Lavender Bunny", "Cherry Dolphin", "Sunny Panda", "Crystal Swan", "Bubble Fox",
  "Mint Dolphin", "Golden Bunny", "Snow Leopard", "Pink Penguin", "Dreamy Otter",
  "Ocean Bunny", "Honey Fox", "Frost Panda", "Ruby Dolphin", "Angel Bunny",
  "Blue Koala", "Pearl Penguin", "Tiny Panda", "Cotton Dolphin", "Moon Fox",
  "Aqua Flamingo", "Velvet Bunny", "Strawberry Panda", "Silver Kitty", "Peach Otter",
  "Crystal Bunny", "Golden Dolphin", "Cherry Penguin", "Sunny Otter", "Lavender Panda",
  "Pink Whale", "Bubble Bunny", "Mint Fox", "Honey Dolphin", "Snowy Panda",
  "Aqua Kitty", "Candy Penguin", "Ruby Bunny", "Ocean Fox", "Velvet Otter",
  "Golden Flamingo", "Blue Bunny", "Pearl Dolphin", "Tiny Fox", "Strawberry Bunny",
  "Crystal Panda", "Moon Dolphin", "Candy Otter", "Frost Fox", "Peach Dolphin",
  "Angel Flamingo", "Mint Panda", "Sunny Bunny", "Silver Penguin", "Cherry Otter",
  "Aqua Panda", "Dreamy Fox", "Pink Koala", "Velvet Penguin", "Golden Panda",
  "Happy Unicorn", "Lucky Panda", "Silly Bunny", "Sleepy Fox", "Magic Dolphin",
  "Sunny Penguin", "Tiny Unicorn", "Cheerful Koala", "Dancing Panda", "Sparkly Bunny",
  "Dreamy Unicorn", "Jolly Otter", "Smiley Fox", "Bouncy Panda", "Glitter Unicorn",
  "Sweet Penguin", "Laughing Bunny", "Cozy Unicorn", "Twinkly Dolphin", "Happy Flamingo",
  "Shiny Panda", "Tiny Dragon", "Puffy Unicorn", "Wiggly Bunny", "Cuddly Fox",
  "Starry Unicorn", "Playful Panda", "Smiling Dolphin", "Rainbow Bunny", "Sunny Unicorn",
  "Fluffy Penguin", "Cheerful Dolphin", "Little Unicorn", "Sparkly Panda", "Happy Koala",
  "Dancing Bunny", "Silly Unicorn", "Lucky Dolphin", "Jelly Panda", "Magic Bunny",
  "Dreamy Penguin", "Bouncy Unicorn", "Sleepy Panda", "Twinkly Bunny", "Giggly Fox",
  "Shimmer Unicorn", "Puffy Panda", "Snuggly Bunny", "Happy Dragon", "Starry Panda",
  "Rainbow Unicorn", "Wobbly Penguin", "Cozy Dolphin", "Tiny Bunny", "Laughing Unicorn",
  "Sunny Panda", "Glitter Fox", "Dancing Unicorn", "Smiley Panda", "Jelly Bunny",
  "Dreamy Unicorn", "Playful Dolphin", "Cheerful Bunny", "Lucky Unicorn", "Puffy Koala",
  "Twinkly Panda", "Sparkle Bunny", "Happy Otter", "Magic Unicorn", "Silly Panda",
  "Fluffy Unicorn", "Smiling Bunny", "Rainbow Dolphin", "Bouncy Fox", "Dream Panda",
  "Sunny Dragon", "Giggly Unicorn", "Star Bunny", "Cozy Panda", "Tiny Dolphin",
  "Glitter Panda", "Wiggly Unicorn", "Dancing Penguin", "Sleepy Unicorn", "Happy Panda",
  "Sparkly Dolphin", "Jolly Unicorn", "Snuggly Panda", "Shiny Bunny", "Lucky Fox",
  "Smiley Unicorn", "Twinkly Penguin", "Cheerful Panda", "Magic Koala", "Puffy Bunny",
  "Rainbow Panda", "Little Dolphin", "Fluffy Dragon", "Dreamy Bunny", "Happy Pegasus",
  "Cute Potato", "Tiny Potato", "Happy Potato", "Sleepy Potato", "Sweet Potato",
  "Chubby Potato", "Smiley Potato", "Baby Potato", "Puffy Potato", "Dancing Potato",
  "Silly Potato", "Cozy Potato", "Jelly Potato", "Sunny Potato", "Snuggly Potato",
  "Dreamy Potato", "Tiny Tater", "Marshmallow Potato", "Glitter Potato", "Bouncy Potato",
  "Fluffy Potato", "Peachy Potato", "Honey Potato", "Wiggly Potato", "Sparkly Potato",
  "Sleepy Tater", "Happy Tater Tot", "Little Potato Bean", "Smol Potato", "Rainbow Potato",
  "Giggly Potato", "Chonky Potato", "Tiny Spud", "Angel Potato", "Warm Potato",
  "Panda Potato", "Cuddly Potato", "Starry Potato", "Jellybean Potato", "Golden Potato",
  "Snuggle Potato", "Silly Spud", "Moon Potato", "Baby Spud", "Puffy Tater",
  "Cozy Spud", "Sugar Potato", "Frosty Potato", "Dancing Spud", "Tiny Tater Bean",
  "Happy Spud", "Bubble Potato", "Dream Spud", "Bunny Potato", "Peach Potato",
  "Sparkle Spud", "Tiny Mash", "Chubby Spud", "Smiley Tater", "Wobbly Potato",
  "Cupcake Potato", "Angel Spud", "Snuggly Tater", "Little Mashy", "Sweet Spud",
  "Tiny Potato Puff", "Cinnamon Potato", "Jelly Spud", "Marshmallow Spud", "Bouncy Tater",
  "Panda Spud", "Cozy Mash", "Honey Spud", "Smol Tater", "Fluffy Spud", "Tiny Potato Pie",
  "Wiggly Spud", "Rainbow Spud", "Sleepy Mash", "Glitter Spud", "Choco Potato",
  "Moon Spud", "Happy Mashy", "Puffy Spud Bean", "Tiny Butter Potato", "Dreamy Tater Tot",
  "Sunny Spud", "Bubble Spud", "Peachy Tater", "Golden Spud", "Smiley Mash",
  "Jelly Tater Tot", "Warm Spud Bean", "Little Potato Puff", "Dancing Tater",
  "Sugar Spud", "Starry Spud", "Cozy Potato Bean", "Tiny Golden Tater", "Snuggle Spud"
];

export function getRandomCutePlayerName(): string {
  const randomIndex = Math.floor(Math.random() * CUTE_PLAYER_NAMES.length);
  const baseName = CUTE_PLAYER_NAMES[randomIndex];
  // Generate a random number with up to 8 digits (from 100 up to 99,999,999)
  const digits = Math.floor(Math.random() * 99999900) + 100;
  return `${baseName}${digits}`;
}
